# Generated by Django 5.1.4 on 2025-07-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
